"""Rumble - PREPARE_ONLY (no official public VOD upload API is documented).

Checked 2026-09-27. What Rumble publishes officially is the **Live Stream API
v1.1** (rumble.com/account/livestream-api): a read-only JSON feed with
follower/subscriber/chat/rant data for overlays. That is a *live stream data*
API, not a VOD upload API. No official, publicly documented endpoint for
uploading a video file exists; upload endpoints are mentioned only as part of
negotiated enterprise/partner packages.

Therefore this provider:

* never calls an undocumented or private endpoint,
* never uses browser automation or scraping,
* prepares ``rumble_ready.mp4`` + ``rumble_metadata.txt`` +
  ``rumble_metadata.json`` for a manual upload in the Rumble web uploader.

If Rumble publishes an official VOD upload API, implement it as a separate
adapter behind ``RUMBLE_MODE=UPLOAD_PRIVATE``; the capability flag below is the
single place that decides.
"""
from __future__ import annotations

import json
import logging
import shutil
import time
from pathlib import Path
from typing import Any, Dict

from app.config import PlatformMode, PlatformStatus
from app.platforms.base import PlatformDiagnosis, PlatformProvider, PlatformResult
from app.platforms.validate import validate_rumble

log = logging.getLogger(__name__)

OFFICIAL_VOD_UPLOAD_API = False
NO_API_NOTE = ("Rumble VOD upload API is not currently verified as an official public API. "
               "Manual upload is required.")


class RumbleProvider(PlatformProvider):
    name = "rumble"
    supports_api_upload = False
    api_summary = ("No official public VOD upload API (the published Rumble API is the "
                   "read-only Live Stream API v1.1) -> PREPARE_ONLY package for a manual "
                   "upload at rumble.com/upload.")

    @property
    def effective_mode(self) -> PlatformMode:
        if OFFICIAL_VOD_UPLOAD_API:
            return self.mode
        return PlatformMode.PREPARE_ONLY

    def is_configured(self) -> bool:
        return True          # nothing to configure for a manual upload

    def validate(self, video: Path) -> Dict[str, Any]:
        return validate_rumble(video, self.settings).as_dict()

    def prepare(self, video: Path, plan, out_dir: Path) -> PlatformResult:
        result = PlatformResult("rumble", PlatformMode.PREPARE_ONLY,
                                PlatformStatus.READY_FOR_MANUAL_UPLOAD)
        check = self.validate(video)
        result.validation = check
        if not check["ok"]:
            result.status = PlatformStatus.FAILED
            result.error = "; ".join(check["errors"])
            return result

        out_dir.mkdir(parents=True, exist_ok=True)
        title = (getattr(plan, "tiktok_title", "") or video.stem).strip()
        description = (getattr(plan, "caption", "") or "").strip()
        tags = [t.lstrip("#") for t in (getattr(plan, "hashtags", []) or [])]

        ready = out_dir / "rumble_ready.mp4"
        if ready.resolve() != video.resolve():
            shutil.copy2(video, ready)

        txt = out_dir / "rumble_metadata.txt"
        txt.write_text(
            f"TITLE\n{title}\n\nDESCRIPTION\n{description}\n\nTAGS\n{', '.join(tags)}\n\n"
            f"CHANNEL\n{self.settings.rumble_channel or '(choose in the uploader)'}\n\n"
            f"LICENSE OPTION\n{self.settings.rumble_license_option}\n\n"
            "HOW TO UPLOAD (manual)\n"
            f"{NO_API_NOTE}\n"
            "1. Open https://rumble.com/upload.php and sign in.\n"
            f"2. Select {ready.name}.\n"
            "3. Paste the title, description and tags above.\n"
            "4. Choose your channel, visibility and licensing option.\n"
            "5. Pick your own thumbnail - none is generated by this application.\n",
            encoding="utf-8")

        meta = {
            "platform": "rumble",
            "mode": PlatformMode.PREPARE_ONLY.value,
            "status": PlatformStatus.READY_FOR_MANUAL_UPLOAD.value,
            "official_vod_upload_api": "NOT VERIFIED",
            "note": NO_API_NOTE,
            "title": title,
            "description": description,
            "tags": tags,
            "channel": self.settings.rumble_channel,
            "license_option": self.settings.rumble_license_option,
            "video_path": str(ready),
            "metadata_text_path": str(txt),
            "validation": check,
            "auto_publish": False,
            "api_calls_made": 0,
            "cover": "selected manually by the user in Rumble",
            "prepared_at": time.time(),
        }
        meta_path = out_dir / "rumble_metadata.json"
        meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")

        result.artifacts = [str(ready), str(txt), str(meta_path)]
        result.metadata = meta
        result.message = NO_API_NOTE
        return result

    def diagnose(self) -> PlatformDiagnosis:
        diag = PlatformDiagnosis(
            platform="rumble", enabled=self.enabled, mode=self.effective_mode,
            configured=True, authenticated=False,
            capability="Official VOD Upload API: NOT VERIFIED -> manual upload REQUIRED",
            required_access="none (manual upload at rumble.com/upload)")
        diag.detail = ("disabled (RUMBLE_ENABLED=false)" if not self.enabled
                       else f"{NO_API_NOTE} Files are prepared for the web uploader.")
        return diag
